### ISSUE TITLE
Research and implement good architectire approach for Django

### ISSUE THREAD

**Issue by pixelsnow** [BeePong/42_transcendence#32]
Classic approach to backend architecture features a layered approach like this:
![Image](https://github.com/user-attachments/assets/82ee61d3-ca49-4139-9379-a9e37ad9d9fa)
We should research whether this is applicable to Django or not and what are best practices to structure our backend code.

**Comment by linhtng** [comment]
AFAIU, it is applicable to Django. Here's Django layer and project structure:

![Image](https://github.com/user-attachments/assets/5f8ff4d4-4c0e-4db8-a022-7cf79bc92e3a)


![Image](https://github.com/user-attachments/assets/5b814ae3-034b-44aa-8c7c-6297a72d4da9)


Reference:
[Mastering Django: Essential Design Patterns and Best Practices](https://www.linkedin.com/pulse/mastering-django-essential-design-patterns-best-mohammad-fa-alfard-zsg3f/)

[Django Project Architecture: The best project skeleton ever](https://rajanmandanka.medium.com/django-project-architecture-the-best-project-skeleton-ever-a184143f1c82)
