### ISSUE TITLE
Bug fix/Implement the wait for db to start before nginx starts

### ISSUE THREAD

**Issue by linhtng** [BeePong/42_transcendence#37]
Currently, when you run our project and go to localhost/, sometimes it just show blank page and even 502 error when you try to refresh. After waiting for a bit, it works normally. We assume that's because it takes time for db to be available, but we are lacking the check for that.
In inception, I have this code in my init_wordpress script:
```
WAIT_INTERVAL=5

# Function to check if mariadb is up and running
check_mariadb() {
    mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -h "$MYSQL_HOSTNAME" -e "SELECT 1;" >/dev/null 2>&1
}

until check_mariadb; do
    echo "Waiting for MariaDB to start..."
    sleep $WAIT_INTERVAL
done
```
We could add something similar to init_beePong.sh. Alternatively, @liocle and @djames9 seem to know how to add an even better health check for the db in compose.yml, so I leave this to you guys.

**Comment by liocle** [comment]
I can take care of that.
