### ISSUE TITLE
BackendFeature/Implementing a remote authentication

### ISSUE THREAD

**Issue by linhtng** [BeePong/42_transcendence#5]
Implement the following authentication system:
OAuth 2.0 authentication with 42

◦ Integrate the authentication system, allowing users to securely sign in.
◦ Obtain the necessary credentials and permissions from the authority to enable
a secure login.
◦ Implement user-friendly login and authorization flows that adhere to best prac- tices and security standards.
◦ Ensure the secure exchange of authentication tokens and user information between the web application and the authentication provider.
This major module aims to get a remote user authentication, providing users with a secure and convenient way to access the web application.

**Comment by pixelsnow** [comment]
- [ ] eat
- [x] sleep
- [x] play with cat
