### ISSUE TITLE
FrontendFeature/Multiple language supports

### ISSUE THREAD

**Issue by linhtng** [BeePong/42_transcendence#9]
The objective is to ensure that your website supports multiple
languages to cater to a diverse user base. Key features and goals include:
◦ Implement support for a minimum of three languages on the website to accommodate a broad audience.
◦ Provide a language switcher or selector that allows users to easily change the website’s language based on their preferences.
◦ Translate essential website content, such as navigation menus, headings, and key information, into the supported languages.
◦ Ensure that users can navigate and interact with the website seamlessly, re- gardless of the selected language.
◦ Consider using language packs or localization libraries to simplify the transla- tion process and maintain consistency across different languages.
◦ Allow users to set their preferred language as a default choice for subsequent visits to the website.

**Comment by wengcychan** [comment]
Not choosing this module
